### ISSUE TITLE
install pyrobolearn error

### ISSUE THREAD

**Issue by wq-wust** [robotlearn/pyrobolearn#51] opened 2020-11-17 08:58 UTC
When I run **$ pip install -e .**

ERROR: Command errored out with exit status 1:
     command: /home/wq/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wq/pyrobolearn/setup.py'"'"'; __file__='"'"'/home/wq/pyrobolearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-31a3tcbj
         cwd: /home/wq/pyrobolearn/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/wq/pyrobolearn/setup.py", line 21, in <module>
        reqs = [str(ir.req) for ir in install_requires]
      File "/home/wq/pyrobolearn/setup.py", line 21, in <listcomp>
        reqs = [str(ir.req) for ir in install_requires]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The same error occurs in the python 3.5/3.6 environment.

**Comment by ChenyangRan** [comment] 2020-11-30 04:35
> When I run **$ pip install -e .**
> 
> ERROR: Command errored out with exit status 1:
> command: /home/wq/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wq/pyrobolearn/setup.py'"'"'; **file**='"'"'/home/wq/pyrobolearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-31a3tcbj
> cwd: /home/wq/pyrobolearn/
> Complete output (7 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/wq/pyrobolearn/setup.py", line 21, in
> reqs = [str(ir.req) for ir in install_requires]
> File "/home/wq/pyrobolearn/setup.py", line 21, in
> reqs = [str(ir.req) for ir in install_requires]
> AttributeError: 'ParsedRequirement' object has no attribute 'req'
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> The same error occurs in the python 3.5/3.6 environment.

Have you solved it?
I have met the same one.

**Comment by ChenyangRan** [comment] 2020-11-30 04:36
> When I run **$ pip install -e .**
> 
> ERROR: Command errored out with exit status 1:
> command: /home/wq/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/wq/pyrobolearn/setup.py'"'"'; **file**='"'"'/home/wq/pyrobolearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-31a3tcbj
> cwd: /home/wq/pyrobolearn/
> Complete output (7 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/wq/pyrobolearn/setup.py", line 21, in
> reqs = [str(ir.req) for ir in install_requires]
> File "/home/wq/pyrobolearn/setup.py", line 21, in
> reqs = [str(ir.req) for ir in install_requires]
> AttributeError: 'ParsedRequirement' object has no attribute 'req'
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> The same error occurs in the python 3.5/3.6 environment.

Have you solved it ?
I have met the same one.

**Comment by lrozo** [comment] 2020-11-30 14:19
Hi all, 

May you please be more specific about the OS you are using, how you are creating the virtual environment and any other steps you followed when facing this problem? That would be useful to try to reproduce the problem you are currently experiencing. 

Best,

Leonel

**Comment by lrozo** [comment] 2020-12-02 16:46
This problem arises due to latest versions of pip. Fixed in the above PR.

**Closed by lrozo** 2020-12-02 16:46 UTC
